# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cfde04e1e2594cac8540a6cfdb15e65a819b81a39d1317ed9c75a92658e72d8be54e081dcf9c4a30b02c4bf12bb8103b0646fff79e175e863e4daee05435983

test:
  secret_key_base: 8e2bbc1ebc143bdfbf021248e97095d4ca87f0538401bb002ac6060aa765b8404fb253bab375772bcb86c73e83301af9682f7eb391c28ae32fec767fb7bd7448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
